# Generated by Django 5.0.6 on 2024-07-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('house_details', models.CharField(max_length=200)),
                ('upazila', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
            ],
        ),
    ]
