# Generated by Django 5.0.6 on 2024-07-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodGroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='house_details',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='district',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='upazila',
        ),
    ]
