# Generated by Django 5.0.6 on 2024-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodGroupsApp', '0004_remove_donor_name_donor_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='host',
        ),
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
